CPPASTDoStatement should have `DoWhile` role
bblfsh/cpp-driver pull request #57
Opened 2019-08-14 02:54 UTC by BFergerson

2019-08-14 07:56 UTC, kuba-- requested changes
Generally LGTM, but tests are failing. Please take a look how UAST has changed and fix fixtures.

2019-08-14 12:55 UTC, dennwc approved these changes

2019-08-14 13:31 UTC, bzz commented
👍 re-generated text fixtures with updated roles also need to be committed for CI to pass.

2019-08-15 13:43 UTC, dennwc approved these changes
LGTM, thanks!

2019-08-15 13:44 UTC, merged