Missing CPPASTRangeBasedForStatement roles
bblfsh/cpp-driver pull request #58
Opened 2019-08-14 03:13 UTC by BFergerson

2019-08-14 07:53 UTC, kuba-- requested changes
The CI is failing, so please fix tests. An output uast will be different, so fixtures has to be modified, as well (I assume).

2019-08-14 12:45 UTC, dennwc approved these changes

2019-08-14 13:32 UTC, bzz commented
Great! But same as in https://github.com/bblfsh/cpp-driver/pull/57#issuecomment-521246710 - update for `./fixtures/*` is missing.

2019-08-18 05:01 UTC, dennwc approved these changes

2019-08-18 05:02 UTC, merged